#
# Module manifest for module 'PwshGitHub'
#
# Generated by: grady.sigler
#
# Generated on: 6/1/18
#

@{

# Script module or binary module file associated with this manifest.
RootModule = "PwshGitHub.psm1"
# Version number of this module.
ModuleVersion = '0.0.1'

# ID used to uniquely identify this module
GUID = 'd8a9ddd9-92dc-451f-a329-178e92c56c7c'

# Author of this module
Author = 'grady.sigler'

# Copyright statement for this module
Copyright = '(c) grady.sigler. All rights reserved.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('Get-GHLabels'
                      'Get-GHIssues')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

}

